logging:
  level: INFO
  loggers:
    com.mutantes: DEBUG

DBConfig:
  Endpoint: ${AWS_DYNAMODB_ENDPOINT:-https://dynamodb.us-east-1.amazonaws.com}
  Region: ${AWS_DEFAULT_REGION:-us-east-1}
  AccessKeyId: ${AWS_ACCESS_KEY_ID}
  SecretKey: ${AWS_SECRET_ACCESS_KEY}

RedisConfig:
  host: ${REDIS_HOST:-localhost}
  port: ${REDIS_PORT:-6379}

maxMatrixSize: ${MAX_MATRIX_SIZE:-5000}
